definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
<<<<<<< HEAD
    weight: -50
    menu_name: main
    parent: ''
    enabled: true
    expanded: false
=======
    weight: -47
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
>>>>>>> 0daa9c79002eb226c3d67db0301f4b5fe56480f5
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
